import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--epoch', type=int, default=100, help='epoch number')
parser.add_argument('--lr', type=list, default=[3e-4, 1e-5], help='learning rate')
parser.add_argument('--batchsize', type=int, default=1, help='training batch size')
parser.add_argument('--trainsize', type=int, default=256, help='training dataset size')
parser.add_argument('--testsize', type=int, default=256, help='testing dataset size')
parser.add_argument('--clip', type=float, default=0.5, help='gradient clipping margin')
parser.add_argument('--decay_rate', type=float, default=0.1, help='decay rate of learning rate')
parser.add_argument('--decay_epoch', type=int, default=40, help='every n epochs decay learning rate')
parser.add_argument('--img_root', type=str, default="E:/Light-Field-new/train_data_gan/train_images/", help='root of image')
parser.add_argument('--gt_root', type=str, default="E:/Light-Field-new/train_data_gan/train_masks/", help='root of gts')
parser.add_argument('--focal_root', type=str, default="E:/Light-Field-new/train_data_gan/train_focal/",help='root of focals')
opt = parser.parse_args()